name: image

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  server:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ ubuntu-latest ]

    steps:
    - name: Checkout 🛎
      uses: actions/checkout@master

    - name: Log in to the Container registry
      uses: docker/login-action@v1.10.0
      if: ${{ github.ref == 'refs/heads/main' || github.ref == 'refs/heads/dev' }}
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Extract metadata (tags, labels) for Docker
      id: meta
      uses: docker/metadata-action@v3.4.0
      if: ${{ github.ref == 'refs/heads/main' || github.ref == 'refs/heads/dev' }}
      with:
        images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}{% raw %}

    - name: Build and push Docker images (main)
      uses: docker/build-push-action@v2.6.1
      if: github.ref == 'refs/heads/main'
      with:
        context: .
        push: true
        tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
        labels: ${{ steps.meta.outputs.labels }}

    - name: Build and push Docker images (dev)
      uses: docker/build-push-action@v2.6.1
      if: github.ref == 'refs/heads/dev'
      with:
        context: .
        push: true
        tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:dev
        labels: ${{ steps.meta.outputs.labels }}
